#include "..\..\script_version.hpp"
private _state = missionNamespace getVariable [SERVO_PEREGRINO_ORGANIZADOR_ITEMS_DRAFT_STATE_VAR, createHashMap]; if !(_state getOrDefault ["hasDraft", false]) exitWith {[true, "ITEMS_DRAFT_DISCARD_NOOP", "Nenhum Draft aberto para descartar.", createHashMap] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
private _draft = _state getOrDefault ["current", createHashMap]; private _mode = _draft getOrDefault ["mode", "NEW"];
if (_mode isEqualTo "NEW") exitWith {
    missionNamespace setVariable [SERVO_PEREGRINO_ORGANIZADOR_ITEMS_DRAFT_STATE_VAR, createHashMapFromArray [["ready", true], ["hasDraft", false], ["current", createHashMap], ["baseline", createHashMap], ["revision", (_state getOrDefault ["revision", 0]) + 1], ["lastAction", "DISCARD_NEW"]]];
    [true, "ITEMS_DRAFT_NEW_DISCARDED", "Draft NEW descartado explicitamente; nada foi persistido.", createHashMap] call ServoPeregrino_Organizador_Nexus_fnc_createResult
};
if !(_mode isEqualTo "EDIT") exitWith {[false, "ITEMS_DRAFT_MODE_INVALID", "Modo de Draft inválido para discard.", createHashMap] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
private _kitId = _draft getOrDefault ["kitId", ""]; private _get = [_kitId] call ServoPeregrino_Organizador_Items_fnc_getKit; if !(_get getOrDefault ["success", false]) exitWith {[false, "ITEMS_DRAFT_DISCARD_SOURCE_MISSING", "Não foi possível recarregar o ItemKit persistido para descartar alterações locais.", createHashMapFromArray [["kitId", _kitId], ["repositoryResult", _get]]] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
private _kit = ((_get getOrDefault ["data", createHashMap]) getOrDefault ["kit", []]); private _now = systemTimeUTC; private _clean = createHashMapFromArray [["version", SERVO_PEREGRINO_ORGANIZADOR_ITEMS_DRAFT_VERSION], ["mode", "EDIT"], ["kitId", _kit # 2], ["baseUpdatedAtUTC", +(_kit # 7)], ["name", _kit # 3], ["preferredTarget", _kit # 4], ["origin", [(_kit # 5)] call ServoPeregrino_Organizador_Items_fnc_deepCopy], ["entries", [(_kit # 8)] call ServoPeregrino_Organizador_Items_fnc_deepCopy], ["dirty", false], ["createdFrom", "REPOSITORY"], ["openedAtUTC", _draft getOrDefault ["openedAtUTC", +_now]], ["lastModifiedAtUTC", +_now]]; _state set ["current", _clean]; _state set ["baseline", [_clean] call ServoPeregrino_Organizador_Items_fnc_deepCopy]; _state set ["revision", (_state getOrDefault ["revision", 0]) + 1]; _state set ["lastAction", "DISCARD_EDIT_RELOAD"]; missionNamespace setVariable [SERVO_PEREGRINO_ORGANIZADOR_ITEMS_DRAFT_STATE_VAR, _state];
[true, "ITEMS_DRAFT_EDIT_DISCARDED", "Alterações locais descartadas e Draft EDIT recarregado do Repository atual.", createHashMapFromArray [["draft", [_clean] call ServoPeregrino_Organizador_Items_fnc_deepCopy]]] call ServoPeregrino_Organizador_Nexus_fnc_createResult
