#include "..\..\script_version.hpp"
params [["_entryType", "ITEM", [""]], ["_className", "", [""]], ["_stateMode", "NONE", [""]], ["_quantity", 1, [0]]];
if (_quantity < 0 || {round _quantity isNotEqualTo _quantity}) exitWith {[false, "ITEMS_DRAFT_QUANTITY_INVALID", "Quantidade precisa ser inteiro não negativo.", createHashMapFromArray [["quantity", _quantity]]] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
if (_quantity isEqualTo 0) exitWith {[_entryType, _className, _stateMode] call ServoPeregrino_Organizador_Items_fnc_removeDraftEntry};
private _type = toUpper _entryType; private _mode = toUpper _stateMode; private _state = missionNamespace getVariable [SERVO_PEREGRINO_ORGANIZADOR_ITEMS_DRAFT_STATE_VAR, createHashMap]; if !(_state getOrDefault ["hasDraft", false]) exitWith {[false, "ITEMS_DRAFT_NOT_OPEN", "Nenhum Draft está aberto.", createHashMap] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
private _draft = [(_state getOrDefault ["current", createHashMap])] call ServoPeregrino_Organizador_Items_fnc_deepCopy; private _entries = [(_draft getOrDefault ["entries", []])] call ServoPeregrino_Organizador_Items_fnc_deepCopy; private _index = _entries findIf {(_x # 1) isEqualTo _type && {(_x # 2) isEqualTo _className} && {(_x # 4) isEqualTo _mode}}; if (_index < 0) exitWith {[false, "ITEMS_DRAFT_ENTRY_NOT_FOUND", "ItemEntry não encontrada no Draft.", createHashMap] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
private _entry = [_entries # _index] call ServoPeregrino_Organizador_Items_fnc_deepCopy; private _oldQty = _entry # 3;
if (_mode isEqualTo "EXACT" && {_quantity > _oldQty}) exitWith {[false, "ITEMS_DRAFT_EXACT_QUANTITY_GROW_FORBIDDEN", "Edição numérica não pode fabricar stateData EXACT. Use + para criar DEFAULT_FULL separado.", createHashMapFromArray [["currentQuantity", _oldQty], ["requestedQuantity", _quantity]]] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
if (_quantity isEqualTo _oldQty) exitWith {[true, "ITEMS_DRAFT_QUANTITY_UNCHANGED", "Quantidade já possui esse valor.", createHashMapFromArray [["draft", _draft]]] call ServoPeregrino_Organizador_Nexus_fnc_createResult};
_entry set [3, _quantity]; if (_mode isEqualTo "EXACT") then {private _states = +(_entry # 5); _states resize _quantity; _entry set [5, _states];};
private _valid = [_entry] call ServoPeregrino_Organizador_Items_fnc_validateItemEntrySemantic; if !(_valid getOrDefault ["success", false]) exitWith {_valid};
_entries set [_index, _entry]; _draft set ["entries", _entries]; _draft set ["dirty", true]; _draft set ["lastModifiedAtUTC", systemTimeUTC]; _state set ["current", _draft]; _state set ["revision", (_state getOrDefault ["revision", 0]) + 1]; _state set ["lastAction", "SET_QUANTITY"]; missionNamespace setVariable [SERVO_PEREGRINO_ORGANIZADOR_ITEMS_DRAFT_STATE_VAR, _state];
[true, "ITEMS_DRAFT_QUANTITY_CHANGED", "Quantidade alterada somente no Draft.", createHashMapFromArray [["entry", _entry], ["draft", [_draft] call ServoPeregrino_Organizador_Items_fnc_deepCopy]]] call ServoPeregrino_Organizador_Nexus_fnc_createResult
