#define SERVO_PEREGRINO_ORGANIZADOR_WEAPONS_DISPLAY_VERSION "0.7-E"
#define SERVO_PEREGRINO_ORGANIZADOR_WEAPONS_SEMANTIC_VERSION "0.7.4.4"
#define SERVO_PEREGRINO_ORGANIZADOR_WEAPONS_BUILD "0.7.4.4-equipment-cba-underbarrel-e1-r4-mission-first"
#define SP_ORG_WEAPONS_RUNTIME "ServoPeregrino_Organizador_Weapons_runtime"
#define SP_ORG_WEAPONS_AUTHORITY "ServoPeregrino_Organizador_Weapons_authority"
#define SP_ORG_WEAPONS_LIVE_TEST "ServoPeregrino_Organizador_Weapons_liveLifecycleTest"
#define SP_ORG_WEAPONS_CATALOG_BASE "ServoPeregrino_Organizador_Weapons_catalogBase"
#define SP_ORG_WEAPONS_CATALOG_ALL "ServoPeregrino_Organizador_Weapons_catalogAll"
#define SP_ORG_WEAPONS_KIT_STORE "ServoPeregrino_Organizador_Weapons_weaponKitStore"
#define SP_ORG_WEAPONS_UI_STATE "ServoPeregrino_Organizador_Weapons_uiState"
#define SP_ORG_WEAPONS_UI_DISPLAY_IDD 7800
#define SP_ORG_WEAPONS_UI_CATALOG_RENDER_LIMIT 250
#define SP_ORG_WEAPONS_UI_CATALOG_WINDOW_SIZE 32

#define SP_ORG_WEAPONS_UI_CATALOG_PROJECTION_VAR "ServoPeregrino_Organizador_Weapons_uiCatalogProjection"
#define SP_ORG_WEAPONS_UI_BASE_CATALOG_ROWS_VAR "ServoPeregrino_Organizador_Weapons_uiBaseCatalogRows"

#define SP_ORG_WEAPONS_UICOMMON_MIN_VERSION "0.1.1"
